### ISSUE TITLE
When adding a project, some controls can improperly move and resize.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1042]
**Reported by JacobKlein on 13 Nov 41245624 10:13 UTC**
It appears that the placement of the "Yes, existing user" control is somehow based on the fields beneath it, but it shouldn't be.

When clicked (or when the text is clicked), it all moves leftward, which is slightly jarring to those that are OCD. This should be a quick fix. I apologize for it's near-insignificance.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1066

**Comment by romw** [comment]
**Commented by JacobKlein on 29 Jan 41332750 03:06 UTC**
In addition to the "Yes, existing user" moving when it shouldn't...

Another related thing I noticed is that, if you select "Yes, existing user" and input a bad email/password combination, click Next, then click Back... you'll see that the input controls are now incorrectly resized to be the full width of the dialog.

I'll attach a screenshot.

**Comment by ChristianBeer** [comment]
This is still the case additionally the wizard has problems resizing the terms of use and clicking "Back" when viewing the terms of use does not go back to project selection.

**Comment by AenBleidd** [comment]
@ChristianBeer. do you know some project that uses "Terms of use" page?

**Comment by AenBleidd** [comment]
Is the original behaviour still an issue? I see little movements but they are really little and I see no picture shown on the original screenshot. Maybe some another steps to reproduce this?
![](http://boinc.berkeley.edu/trac/raw-attachment/ticket/1066/Inputs%20full%20width.png)

**Comment by AenBleidd** [comment]
Behaviour mentioned by @ChristianBeer is fixed in #2547

**Comment by JacobWKlein** [comment]
Vitalii asked me about this. Here is my reply:

-------------
Hi Vitalii,

You found me. The issue still exists.

Basically, when you toggle between the radio buttons "No, new user" and "Yes, existing user", you'll see that the text boxes are wider for the "Yes, existing user" scenario.

If you decided to fix this, the fix would be to have the right-justified labels all be the same width regardless of which radio button is selected, and then also keep all the text boxes the same width regardless of which radio button is selected.

I know it's trivial. But it's unnecessarily jarring.

Hope that helps explain it!
Thanks,
Jacob
