### ISSUE TITLE
GUI Glitch - Actions on 2+ selected rows appear to leave every other row unselected

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1083]
**Reported by JacobKlein on 8 Jun 41333780 03:33 UTC**
If 2+ rows are selected, and an action is performed (like "Show Graphics"), the UI then shows only every other row selected, but actions indicate the initial rows are still selected (like "Properties" is greyed out)

Another example would be clicking "Copy" when having several consecutive rows selected in the Event Log.

An even more interesting case would be clicking "Copy" when having several random rows selected in the Event Log.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1107

**Comment by ChristianBeer** [comment]
Does not happen in current 7.6.33

**Comment by AenBleidd** [comment]
@ChristianBeer Please reopen this issue. It still can be reproduced:
1 - Select several strings
2 - Click 'Cope selected' button

![image](https://cloud.githubusercontent.com/assets/3234209/24807056/735d8072-1bbf-11e7-8ded-715c1aafbc6f.png)

**Comment by Ageless93** [comment]
But if you then actually paste the contents of clipboard into a file,
you'll see that all the lines are there.
So it's just an optical illusion, it's not as if only the coloured lines
have been copied. All the ones you selected previously have been actually
copied.


-- Jord van der Elst.

**Comment by ChristianBeer** [comment]
I assume you are on Windows. I just tried it again and this does not happen on Linux. Reopening either way as it should be fixed. Even if it is only an optical illusion.

**Comment by AenBleidd** [comment]
@Ageless93 You're right but it is a GUI glitch still.
@ChristianBeer Yes, I've reproduced it on Win7/8.1/10 so this is a common wxWidgets Windows problem I guess

**Comment by CharlieFenton** [comment]
I just tested this on 7.6.33 and it does not happen on a Mac, though I can easily reproduce it on MS Windows 7.

**Comment by Ageless93** [comment]
Any progress on this?

**Comment by AenBleidd** [comment]
@Ageless93, no progress now. I'll try to build BOINC with updated wxWidgets to see whether this is still an issue. If it is I'll try to fix it either on BOINC side or on wxWidgets side.

**Comment by AenBleidd** [comment]
Fixed in #2137

**Comment by Ageless93** [comment]
Tested with BOINC Manager built from Master. It's fixed in that one.

**Comment by Ageless93** [comment]
Although now the effect is:
- select rows.
- do action (like suspend)
- this does suspend all selected rows.
- this does however also no longer high light those rows.
- clicking resume will resume all selected rows.

**Comment by AenBleidd** [comment]
This was a glitch in Log window. It is still reproducible. I'll rewrite the
pull request with fix soon.

Best regards,
Vitalii

Sent via Android

24 окт. 2017 г. 18:25 пользователь "Jord van der Elst" <
notifications@github.com> написал:
