### ISSUE TITLE
cross-project certificate broken by bad external link

### ISSUE THREAD

**Issue by marius311** [BOINC/boinc#2690]
A user pointed out that the cert_all page is broken, which I've tracked down to that:

https://github.com/BOINC/boinc/blob/5a42f595cbb3e337863bee9395143b90e2690f37/html/inc/user.inc#L36-L37

is a broken link. E.g. for my user on Cosmology@Home the link is http://boinc.netsoft-online.com/get_user.php?cpid=da600bb3c0e54c1327d76a64b04fec36 which gives a forbidden error.

Does anyone know the correct URL?

**Comment by marius311** [comment]
Ah, I see this is "answered" here: https://lists.ssl.berkeley.edu/pipermail/boinc_dev/2017-April/022648.html

We should display a better error message for projects that aren't "whitelisted" by boinc.netsoft-online.com. I will work on that.

**Comment by nilsjh** [comment]
The broken cross project certificate is still part of the code. For LHC@home, we have replaced the broken PHP with a link to available cross project statistics sites. 

Another option would be to simply drop the cross project statistics page cert_all.php.  I noticed that a number of projects have the default page with ugly php messages. (E.g. https://setiathome.berkeley.edu/cert_all.php )

**Comment by sergeyklay** [comment]
The issue has been fixed by James Drews. The issue might be closed.

/cc @davidpanderson

**Comment by marius311** [comment]
Was this fixed BOINC-wide somehow, or were you just able to get your project added? I still see the error from a site which isn't white-listed.

**Comment by sergeyklay** [comment]
Oh! This related only to https://boinc.thesonntags.com website. For more see comments here: https://github.com/BOINC/boinc/issues/2975
