### ISSUE TITLE
[Web] Redirect from http to https

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2731]
The boinc.berkeley.edu doesn't redirect to the https://boinc.berkeley.edu address, so in default it uses the http protocol.

**Comment by davidpanderson** [comment]
Fixed in #2733

**Comment by adamradocz** [comment]
The sub pages, like [http://boinc.berkeley.edu/wiki/User_manual](http://boinc.berkeley.edu/wiki/User_manual), still have this issue

**Comment by AenBleidd** [comment]
Works for me in:
IE 11
Chrome 69
Edge 40
I have no Firefox installed to verify.
@adamradocz, what browser/os do you use? Could you please attach some screenshots here?
Thanks

**Comment by adamradocz** [comment]
I have the latest Chrome (v70).

![capture](https://user-images.githubusercontent.com/16503773/47435893-b8837a00-d7a5-11e8-802b-63e01b754946.PNG)

**Comment by AenBleidd** [comment]
Sorry, I thought I'm answering a different ticket. My bad. Yes, the same behavior on my side.
Looks like redirect works for the main page only.
I think for the wiki pages it should be configured separately
