### ISSUE TITLE
BOINC on Android cannot add Science united and GRCPool project

### ISSUE THREAD

**Issue by fckwan** [BOINC/boinc#3440]
**Describe the bug**
BOINC on Android cannot add science united or GRCPool  as an account manager

**Steps To Reproduce**
1. From BOINC on Android, select add project, then add account manager 
2. select the related project (Science united or GRCPool) . Put in user name and password
3. It will result in failed

**Expected behavior**
Account manager added to BOINC on Android.

**Screenshots**
Science United 
https://photos.app.goo.gl/ULQNo8uqTzTff61Y7
GRCPool
https://photos.app.goo.gl/p137sqenUrJEicrz9

**System Information**
 - OS: Android 9
 - BOINC Version:  7.16.3

**Additional context**
GRCPool was not listed as an account manger in earlier version. But that is no longer the case. 
the following video on BOINC for android is outdated.
https://www.grcpool.com/help/videos

**Comment by AenBleidd** [comment]
It was working when I checked this last time. Are you sure you put username where username is required but not email and vice versa? 
In any case I'll check this one more time this week,

**Comment by AenBleidd** [comment]
@fckwan, BTW, you can add only one account manager. If there is a possibility to try to add another account manager without removing the existing connection - this should be fixed separately

**Comment by fckwan** [comment]
For Science United. Username = Email address. 
And I used email address /password and still get failed error message.

**Comment by AenBleidd** [comment]
@fckwan, did you try to add several AMs at the same time?
I can't reproduce your issue,

**Comment by fckwan** [comment]
Hi, I double checked. 
It was caused by I already have another account manager added (BAM!) and try to add a second account manager.
Please close this issue.
