### ISSUE TITLE
Recommended Version Logic ignores OS Version requirements

### ISSUE THREAD

**Issue by CharlieFenton** [BOINC/boinc#4116]
Although the examples and specific cases I have listed here are for Macintosh, this issue applies to all platforms.

This bug has four parts:

[1] The web logic which determines which "Recommended version" to offer a user fails to take into account the minimum version of the operating system each version of BOINC may require, or the CPU architecture it supports. For example, the latest version of BOINC for Macintosh (BOINC 7.16.14) requires at least MacOS 10.9.0, but it is shown on https://boinc.berkeley.edu/download.php for all Macintosh users including those running MacOS 10.7.5. It should instead offer the most recent recommended version for MacOS 10.7.5, which is BOINC 7.16.11.

In addition, BONC has builds available for PowerPC Macs, 32-bit Intel Macs, 64-bit Intel Macs and now the new arm64 "Apple Silicon" Macs. The web logic needs to take all these factors into account.

[2] Similarly, the code in the BOINC client which checks for a new version of BOINC fails to consider the version of the operating system or the CPU architecture. When BOINC 7.16.13 was released for macOS 10.9+, the client incorrectly told users running older versions of MacOS that a newer version is available for their computers.

[3] The BOINC wiki page https://boinc.berkeley.edu/wiki/System_requirements is misleading where it says:
> Operating system
Mac OS X 10.4.0 and later
Hardware
Macintosh computer with an Intel x86 or PowerPC G3, G4, or G5 processor

As an illustration of the confusion this causes, a user wrote [here](https://boinc.berkeley.edu/forum_thread.php?id=14054&postid=101759):
> the wiki says that the minimum system requirement is mac os 10.4, and i'm running 10.7.5 on a nice little i7-powered mini server. so, i think, i meet the minimum

The wiki page should somehow make clear that BOINC has builds available for each of these configurations, but some are supported only by older versions.

[4] The [download all page](https://boinc.berkeley.edu/download_all.php) needs a separate section for "MacOS (64-bit Intel and Apple Silicon) version 10.9.0+". 

The section "Mac OS X (64-bit Intel) Version 10.7.0+" should be changed to "MacOS (64-bit Intel) Version 10.7.0 - 10.15.7".

The section "Mac OS X (32-bit or 64-bit Intel) Version 10.4.0+" should be changed to "MacOS (32-bit or 64-bit Intel) Version 10.4.0 - 10.15.7".

The section "Mac OS X (Power PC or 32-bit Intel) Version 10.4.0+" should be changed to "MacOS (Power PC or 32-bit Intel) Version 10.4.0 - 10.5.8".

Note that Apple no longer uses the name "OS X" and has replaced it with MacOS.

**Comment by CharlieFenton** [comment]
Items [1], [3] and [4] are resolved. 

Unfortunately, issue [2] requires changes to the BOINC client as well as the server. Existing BOINC clients will still be telling people that a new version is available when that new version is only for Macs with newer operating systems. At this point, that only affects those running MacOS 10.8.5 or earlier. That version of MacOS was released on 13 August 2015 so that should represent a fairly small portion of BOINC users. The relevant client code does not send the OS version to the server when it queries about a new BOINC version. This needs to be updated in a future version of BOINC, as well as in the server code.

However, I believe that when these users click on the link to update their client, the new web logic (from item [1]) will offer them the BOINC version they already have.

**Comment by davidpanderson** [comment]
Fixing [2] will require including min/max OS versions in the XML descriptions of BOINC versions.

**Comment by AenBleidd** [comment]
@CharlieFenton, wasn't this already fixed or smth is still missing?

**Comment by CharlieFenton** [comment]
Fixed by #4685
