### ISSUE TITLE
BOINC doesn't run on Mint like it use too

### ISSUE THREAD

**Issue by Sandman192** [BOINC/boinc#6382]
### Describe the bug

BOINC use to run on Mint 19 but when 22 came out it will not run at all. You have to use Flatpack to make it work.
True you can tell Mint to run at startup but...
Things you can't do but are minimal is you get no icon on the bottom right and you can't close window without closing the program.

Other issues running Flatpack is, Notification is all black and the Window that pops up at the start to ask for what project or project manger to use are blank.

The biggest issues is, don't know if it's because of running it under Flatpack is it doesn't ask for what Drive to use for all your Project Data. You know because SDDs and Linux is installed on.

BOINC please get with the times when Mint upgrades from time to time and keep BOINC running on Mint...

**Comment by AenBleidd** [comment]
So what's the issue with Mint 22?
How did you install BOINC in the first place?
Have you used the package from here: https://boinc.berkeley.edu/linux_install.php ?
Flatpack is another topic, and should be investigated separately.

**Comment by Sandman192** [comment]
> So what's the issue with Mint 22? How did you install BOINC in the first place? Have you used the package from here: https://boinc.berkeley.edu/linux_install.php ?

Yes, I used BOINC for Linux x64 Ubuntu 24.02 stable BOINC v8.0.2.

This is what BOINC download sit is giving me instead for Ubuntu 24.02 to install below. But "buster" is fixed mow but use to showed $(lsb_release -cs) instead. I see nothing to point the command to use 24.02. The same for Debian in 10, 11, 12.

`sudo curl -fsSL https://boinc.berkeley.edu/dl/linux/stable/buster/boinc.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/boinc.gpg`

But what's in the second command doesn't appear to be right. $(dpkg --print-architecture) seems wrong. I believe this is suppose to tell the terminal to use 24.02.

`sudo echo deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/boinc.gpg] https://boinc.berkeley.edu/dl/linux/stable/noble noble main | sudo tee /etc/apt/sources.list.d/boinc.list > /dev/null`

`sudo apt update`

`sudo apt install boinc-client boinc-manager`

`Debian had the same issue with $(lsb_release -cs) which was fixed and replaced with "bookworm" but $(dpkg --print-architecture) has not changed.`

**Comment by AenBleidd** [comment]
1. There is no Ubuntu 24.02. Correct version is 24.04
2. What do you mean `$(dpkg --print-architecture)` is wrong? Do you see any error in the output?
3. I still don't understand what exactly is your issue on Mint.

**Comment by Sandman192** [comment]
> 1. There is no Ubuntu 24.02. Correct version is 24.04
It's a typo.
> 2. What do you mean `$(dpkg --print-architecture)` is wrong? Do you see any error in the output?
Well see if this command works. But for now I have to wait till the Flatpack version is done with the work it's already singed.
> 3. I still don't understand what exactly is your issue on Mint.
First the code was wrong and kept getting a 404 web access err when `$(lsb_release -cs)` is a web code and not a Linux terminal code and now just got fixed after I reported the problem.
Second BOINC would not run.
Again for now I'll wait for work to be done on the Flatpack version and try again later.

**Comment by AenBleidd** [comment]
Ok, I'm closing this for now as there is not clear explanation about the issue.
When you have one - please make sure to make in detailed or at least specify what's exactly wrong.

**Comment by Sandman192** [comment]
BOINC from Flatpak is uninstalled.
Standard BOINC Installed and is running.
